spring.application.name=messaging_microservice
spring.mongodb.uri=mongodb://localhost:27017
spring.mongodb.database=vaultchat
server.port=9001

app.uri.device-microservice=http://localhost:9000
app.uri.user-microservice=http://localhost:9003
app.uri.social-microservice=http://localhost:9002
app.uri.messaging-microservice=http://localhosr:9001