spring:
    application:
        name: device-microservice
    mongodb:
        uri: mongodb://localhost:27017
        database: vaultchat

server:
    port: 9000

app:
    uri:
        device-microservice: http://localhost:9000
        user-microservice: http://localhost:9003
        social-microservice: http://localhost:9002
        messaging-microservice: http://localhosr:9001