plugins {
    alias libs.plugins.java
    alias libs.plugins.spring.boot
    alias libs.plugins.spring.boot.dependency.management
    id 'org.jetbrains.kotlin.jvm'
}

group = 'dev.jason.project'

repositories {
    mavenCentral()
}

dependencies {
    implementation projects.core
    
    implementation libs.spring.boot.starter.data.mongodb
    implementation libs.spring.boot.starter.webmvc
    
    compileOnly libs.lombok
    annotationProcessor libs.lombok
    
    testImplementation libs.spring.boot.starter.data.mongodb.test
    testImplementation libs.spring.boot.starter.webmvc.test
    
    testCompileOnly libs.lombok
    testRuntimeOnly libs.junit.platform.launcher
    testAnnotationProcessor libs.lombok
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

tasks.named('test') {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(25)
}
