spring:
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        -   id: device-route
                            uri: https://vaultchat-device-microservice.onrender.com
                            predicates:
                                - Path=/device/**

                        -   id: user-route
                            uri: https://vaultchat-user-microservice.onrender.com
                            predicates:
                                - Path=/user/**

                        -   id: social-route
                            uri: https://vaultchat-social-microservice.onrender.com
                            predicates:
                                - Path=/social/**

                        -   id: messaging-route
                            uri: https://vaultchat-messaging-microservice.onrender.com
                            predicates:
                                - Path=/messaging/**

app:
    uri:
        device-microservice: https://vaultchat-device-microservice.onrender.com
        user-microservice: https://vaultchat-user-microservice.onrender.com
        social-microservice: https://vaultchat-social-microservice.onrender.com
        messaging-microservice: https://vaultchat-messaging-microservice.onrender.com