plugins {
    alias libs.plugins.java
    alias libs.plugins.java.library
	alias libs.plugins.spring.boot
	alias libs.plugins.spring.boot.dependency.management
}

group = 'dev.jason.project.spring'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
	compileOnly libs.lombok
    annotationProcessor libs.lombok
    
    implementation libs.firebase.admin

    implementation libs.spring.boot.starter.webmvc

    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}

test {
    useJUnitPlatform()
}
