spring:
    mongodb:
        uri: ${MONGODB_URI}

server:
    port: 8080

app:
    uri:
        device-microservice: https://vaultchat-device-microservice.onrender.com
        user-microservice: https://vaultchat-user-microservice.onrender.com
        social-microservice: https://vaultchat-social-microservice.onrender.com
        messaging-microservice: https://vaultchat-messaging-microservice.onrender.com