plugins {
	alias libs.plugins.java
	alias libs.plugins.spring.boot
	alias libs.plugins.spring.boot.dependency.management
}

group = 'dev.jason.project'

repositories {
	mavenCentral()
}

dependencies {
	
	implementation projects.core

	implementation projects.microservices.deviceMicroservice
	implementation projects.microservices.messagingMicroservice
	implementation projects.microservices.socialMicroservice
	implementation projects.microservices.userMicroservice

	implementation platform(libs.spring.cloud.dependencies)
	implementation libs.spring.boot.starter.gateway.server.webmvc

	implementation libs.spring.boot.starter.data.mongodb
	implementation libs.spring.boot.starter.webmvc

	testImplementation libs.spring.boot.starter.webmvc.test
	testRuntimeOnly libs.junit.platform.launcher
}

tasks.named('test') {
	useJUnitPlatform()
}
